recording:
  sample_rate: 16000
  channels: 1
  format: "m4a"
  bitrate: "128k"
  
transcription:
  model: "whisper-1"
  language: "en"  # or null for auto-detect
  response_format: "text"  # for timestamps
  temperature: 0  # deterministic output
  
summarization:
  model: "google/gemini-2.5-flash"
  max_tokens: 2000
  temperature: 0.3
  chunk_chars: 4000
  chunk_overlap_paragraphs: 1
  
storage:
  recordings_dir: "./recordings"
  temp_dir: "./temp"
