recording:
  # Higher quality audio settings for M3 Pro
  sample_rate: 48000  # Studio quality (was 16000)
  channels: 1  # Keep mono for smaller files and clarity
  bitrate: '128k'  # Better quality (was 96k)
  # Optional: Add noise reduction settings
  blocksize: 2048  # Keep this for good latency
  
transcription:
  model: "whisper-1"
  language: "en"  # or null for auto-detect
  response_format: "text"  # for timestamps
  temperature: 0  # deterministic output
  preprocess_audio: true
  highpass_hz: 100
  loudnorm: true
  loudnorm_settings: "I=-23:LRA=7:TP=-2"
  
summarization:
  model: "anthropic/claude-3.5-haiku"
  max_tokens: 4000
  temperature: 0.1
  chunk_chars: 8000
  chunk_overlap_paragraphs: 2
  
storage:
  recordings_dir: "./recordings"
  temp_dir: "./temp"
