recording:
  sample_rate: 16000
  channels: 1
  format: "m4a"
  bitrate: "96k"
  
transcription:
  model: "whisper-1"
  language: "en"  # or null for auto-detect
  response_format: "verbose_json"  # for timestamps
  temperature: 0  # deterministic output
  
summarization:
  model: "anthropic/claude-sonnet-4.5"
  max_tokens: 2000
  temperature: 0.3
  
storage:
  recordings_dir: "./recordings"
  temp_dir: "./temp"
