recording:
  # Higher quality audio settings for M3 Pro
  sample_rate: 48000  # Studio quality (was 16000)
  channels: 1  # Keep mono for smaller files and clarity
  bitrate: '128k'  # Better quality (was 96k)
  # Optional: Add noise reduction settings
  blocksize: 2048  # Keep this for good latency
  
transcription:
  model: "whisper-1"
  language: "en"  # or null for auto-detect
  response_format: "text"  # for timestamps
  temperature: 0  # deterministic output
  
summarization:
  model: "anthropic/claude-3.5-haiku"  # Changed from gemini to claude haiku
  max_tokens: 4000
  temperature: 0.1

  # Chunking settings - UPDATED for better context preservation
  chunk_chars: 6000  # Reduced from 8000 for more manageable chunks
  chunk_overlap_paragraphs: 5  # Increased from 2 to 5 for better context overlap
  
storage:
  recordings_dir: "./recordings"
  temp_dir: "./temp"